version: '3'

services:
  express:
    build: ./
    image: users_microservice
    container_name: users
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/postgres
    networks:
      - dev-net
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres
    container_name: users-db
    volumes:
      - users-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - dev-net
    ports:
      - 3001:5432

networks:
  dev-net:
    driver: bridge

volumes:
  users-db-data:
    driver: local
