openapi: '3.0.0'

# -----------------------------------------------------------------------------

info:
  title: 'Users Microservice'
  description: >
    Part of the **Seedy FIUBA Project** ([view it on GitHub](https://github.com/orgs/SeedyFiuba-G8/)).
  version: '1.0.0'

# -----------------------------------------------------------------------------

servers:
  - url: http://sf-tdp2-users.herokuapp.com/
    description: 'Production'
  - url: http://sf-tdp2-users-dev.herokuapp.com/
    description: 'Staging'
  - url: http://localhost:3000/
    description: 'Local development'

# -----------------------------------------------------------------------------

tags:
  - name: Admins
  - name: Users
  - name: Status

# -----------------------------------------------------------------------------

paths:
  # STATUS
  /ping:
    get:
      tags:
        - Status
      responses:
        200:
          $ref: '#/components/responses/ping'

  /health:
    get:
      tags:
        - Status
      responses:
        200:
          $ref: '#/components/responses/ping'

# -----------------------------------------------------------------------------

components:
  responses:
    health:
      description: Microservice general health state reported.
      content:
        application/json:
          schema:
            type: object
            properties:
              database:
                type: string
                example: 'UP'

    ping:
      description: Server is active.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                example: 'ok'
#
# -----------------------------------------------------------------------------
