name: CI
on: [push, pull_request]

jobs:
    run_tests:
        runs-on: ubuntu-latest
        env:
            CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test
            - uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    async_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run ESLint
              run: npm run lint
    build_and_push:
        runs-on: ubuntu-latest
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            HEROKU_EMAIL: ${{ secrets.HEROKU_MAIL }}
        needs: [run_tests, async_lint]
        steps:
            - uses: actions/checkout@master
            - name: Build Container
              run: docker build -t users_microservice_dev .
            - name: Tag Container
              run: docker tag users_microservice_dev registry.heroku.com/sf-tdp2-users-dev/web
            - name: Push Container
              run: docker push registry.heroku.com/sf-tdp2-users-dev/web
            - name: Release Container
              run: heroku container:release web --app sf-tdp2-users-dev
